module.exports=(error,req,res,next)=>{
    error.statusCode=error.statusCode||500;
    res.status(error.statusCode).json({
        status:error.status,
        message:error.message,
        stackTrace:error.stack,
        error
    })
}